server:
  port: 8081
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 106.55.60.108:8848
management:
  endpoints:
    web:
      exposure:
        include: \\*
